language: python

# Use the new container-based Travis infrastructure.
sudo: false

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

# Try OS X.
os:
  - linux
  #- osx

env:
   # shorten logging of pip-accel
   - PIP_ACCEL_LOG_FORMAT="%(name)-18s %(levelname)s %(message)s"
#  - PYCRYPTO_VERSION=2.4.1
#  - PYCRYPTO_VERSION=2.6.1

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python 3.6
      - python: "nightly"
      # Ignore failures from OS X.
      - os: osx

addons:
  apt:
    packages:
    # TODO Review installing dependencies.
    # NB: Travis-CI uses Ubuntu 12.04 TLS, thus these are only
    #     available for Python 2.7.
    - python-imaging
    - python-gst0.10
    #- python-matplotlib  # outdated: v1.1.1
    - python-mysqldb
    # required to build lxml
    - libxml2-dev
    - libxslt1-dev
    - python-numpy
    - python-pyodbc
    - python-qt4
    - python-scipy
    - python-wxgtk2.8
    - libespeak1  # required by pyttsx

before_install:
  # Compile bootloader
  - cd bootloader
  - python waf distclean all --no-lsb
  - cd ..


install:
  # Install PyInstaller.
  - pip install -e .

  # Install dependencies for tests. Use pip-accel to cache compiled
  # packages and safe recompiling each time.
  # Download-progress bars break Travis's log view. Disable them by
  # piping output through another program (if output is not a tty, no
  # progress bars)
  - pip install pip-accel | cat
  - pip-accel install -r tests/requirements-tools.txt | cat
  - pip-accel install -r tests/requirements.txt | cat

script:
  # Run tests and speed them up by sending them to multiple CPUs.
  # Run unitttest first.
  - py.test -n 5  --maxfail 3 tests/unit/ tests/

notifications:
    irc:
        channels:
            - "irc.freenode.org#pyinstaller"
        use_notice: true
        # skip_join: true would require +n mode *not to be set on #pyinstaller
        skip_join: false
