language: python

# Use the new container-based Travis infrastructure.
sudo: false

branches:
  except:
    - /pyup-.*/

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip

# Try OS X.
os:
  - linux

env:
#  - PYCRYPTO_VERSION=2.4.1
#  - PYCRYPTO_VERSION=2.6.1

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python 3.6
      - python: "nightly"
      # Ignore failures from OS X.
      - os: osx
  include:
      # Use generic language for osx
      - os: osx
        sudo: required
        language: generic
        python: "3.6"

addons:
  # Ubuntu 12.04 (LTS) packages installed into this Travis-CI container. Since
  # Ubuntu 12.04 provides *NO* Python 3 packages prefixed by "python3-", only
  # Python 2.7 packages prefixed by "python-" are installable. Installing only
  # Python 2.7 packages would be useless, however! Python packages should thus
  # be installed by "pip" via the "test/requirements-library.txt" specification.
  #
  # Travis-CI intends to add support for Ubuntu 14.04 (LTS) at some future date.
  # To track progress on this long-standing issue, see:
  #
  #     https://github.com/travis-ci/travis-ci/issues/2046
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - gfortran
    - libatlas-base-dev

before_install:
  - SECONDS=0 && function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  # Skip build if the commit message contains [skip travis] or [travis skip]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true

  # Perform the manual steps on osx to install python3 and activate venv
  - >
      if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          brew update;
          brew install python3;
          python3 -m venv venv;
          source venv/bin/activate;
      fi

  # Compile bootloader
  - cd bootloader
  - python waf distclean all
  - cd ..


install:
  # Update pip.
  - python -m pip install -U pip setuptools wheel

  # Install dependencies for tests.
  - pip install -U -r tests/requirements-tools.txt -r tests/requirements-libraries.txt

  # Install PyInstaller.
  - pip install -e .


script:
  # Run tests and speed them up by sending them to multiple CPUs.
  # Run unitttest first.
  # Timeout before travis does so that the cache is always updated.
  - timeout $((2760 - $SECONDS)) py.test -n 3 --maxfail 3 tests/unit tests/functional

notifications:
    irc:
        channels:
            - "irc.freenode.org#pyinstaller"
        use_notice: true
        # skip_join: true would require +n mode *not to be set on #pyinstaller
        skip_join: false
