language: python

branches:
  except:
    - /pyup\/.*/

# Make sure we are on Ubuntu 16.04. This fixes the following error, which
# appears on Trusty (Ubuntu 14.04) when testing Linux Python 3.5 and 3.6 with
# PyQt5 5.12: ``relocation error: /tmp/_MEIFdpiBr/libQt5DBus.so.5: symbol
# dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not
# defined in file libdbus-1.so.3 with link time reference``.
dist: xenial

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/py37

os:
  - linux

services:
  # PyQt5 tests require a GUI. See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb.
  - xvfb

env:
  global:
    # Obtain diagnostic information from Qt about each plugin it tries to load.
    - QT_DEBUG_PLUGINS=1

jobs:
  fast_finish: true
  include:
    - &test-pyinstaller
      stage: Test - PyInstaller
      python: 3.7
      script:
        # -n 3
        #   Run tests and speed them up by sending them to multiple CPUs.
        #
        # --maxfail 3
        #   End tests after 3 failures.
        #
        # --durations 10
        #   Print the 10 longest tests; see
        #   https://docs.pytest.org/en/latest/usage.html#profiling-test-execution-duration
        - >
          pytest -n 3 --maxfail 3 --durations 10
          tests/unit tests/functional
          --ignore tests/functional/test_libraries.py

    - &test-libraries
      stage: Test - Libraries
      python: 3.7
      before_install:
        # Install OpenSSL 1.1. This fixes dynamic linking problems when PyQt5.13 tries
        # to link with OpenSSL 1.1 -- on Ubuntu 16 (xenial), the older OpenSSL
        # produces errors like ``qt.network.ssl: QSslSocket: cannot resolve
        # OPENSSL_init_ssl``.
        - sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl -y
        - sudo apt-get update -q
        - sudo apt install openssl -q
      script:
        - >
          pytest -n 3 --maxfail 3 --durations 10
          tests/functional/test_libraries.py
        # The ``run_tests`` script is invoked with the ``-c`` option to
        # specify a ``pytest.ini``, rather than allowing pytest to find
        # something unexpected in the filesystem (it searches from the root
        # dir all the way to the top of the filesystem per
        # https://docs.pytest.org/en/latest/customize.html).
        - python -m PyInstaller.utils.run_tests -c PyInstaller/utils/pytest.ini --include_only=pyi_hooksample.

    - <<: *test-pyinstaller
      python: 3.5
    - <<: *test-libraries
      python: 3.5

    - <<: *test-pyinstaller
      python: 3.6
    - <<: *test-libraries
      python: 3.6

    - <<: *test-pyinstaller
      python: 3.8
    - <<: *test-libraries
      python: 3.8

    - <<: *test-pyinstaller
      python: nightly
    - <<: *test-libraries
      python: nightly

  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python
      - python: "nightly"

addons:
  # Python packages should be installed by "pip" via the "test/requirements-library.txt" specification.
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - gfortran
    - libatlas-base-dev
    # Per https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041363.html,
    # PyQt5 5.12 needs a library not installed by default.
    - libxkbcommon-x11-0

install:
  # Update pip.
  - python -m pip install -U pip setuptools wheel | cat

  # Install dependencies for tests.
  - pip install --progress-bar=off -U -r tests/requirements-tools.txt -r tests/requirements-libraries.txt

  # Install PyInstaller Hook Sample, to ensure that tests declared in
  # entry-points are discovered.
  - pip install https://github.com/pyinstaller/hooksample/archive/v4.0rc1.zip

  # Compile bootloader
  - cd bootloader
  - python waf distclean all
  - cd ..

  # Install PyInstaller.
  - pip install --progress-bar=off -e .

  # Make sure the help options print.
  - python -m pyinstaller -h

script:
  - true

notifications:
    irc:
        channels:
          - "irc.freenode.org#pyinstaller"
        use_notice: true
        # skip_join: true would require +n mode *not to be set on #pyinstaller
        skip_join: false
