---
name: Validate new news entries

on:
  pull_request:  # Trigger on PRs to develop and v4
    branches:
      - develop
      - v4

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate new news items
        run: python scripts/verify-news-fragments.py

      - name: Install towncrier
        run: pip install -q -U setuptools wheel towncrier

      - name: Run towncrier
        run: towncrier --draft
